server:
  port: 8888

spring:
  profiles:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 817137133374-5s5ubeg76kr2g38ogidukpt6j8jh8lrf.apps.googleusercontent.com
            client-secret: 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

logging.level:
  org.hibernate:
    SQL: debug
    type.descriptor.sql: trace

jwt:
  secret: mochus36lZoj3DdSsarTsDQ1g7DxJln32qlCKRb4DCwRWUOHuGactEN7Qp1krla8
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/springbatch
    driver-class-name: org.h2.Driver
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/readme?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gh
    password: 1111
