spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springbatch
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate:
    SQL: debug
    type.descriptor.sql: trace
